name: eda
# name: mlflow-3813ae8458540c147145783f776fc46a589d326c
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter #=3.0.12 #manual
  - seaborn #=0.11.1
  - pandas=1.2.3
  # - pip=20.3.3
  - numpy<=1.19.5
  - pandas-profiling
  - pyarrow
  - wandb 
  # - pip:
  #     - wandb==0.10.31